# Generated by Django 5.2 on 2025-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
