# Generated by Django 5.2 on 2025-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
